version: '3.8'

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-sweb
    volumes:
      - ./sweb.ini:/etc/letsencrypt/sweb.ini:ro
      - ./letsencrypt:/etc/letsencrypt
      - ../:/app:ro  # mount the repo root
    entrypoint: sh
    command:
      - -c
      - >
        pip install /app &&
        certbot certonly
          --authenticator dns-sweb
          --dns-sweb-credentials /etc/letsencrypt/sweb.ini
          --dns-sweb-propagation-seconds 900
          -d example.com -d '*.example.com'
