version: '3'
services:
    certbot:
        build: .
        volumes:
            - ./sweb.ini:/etc/letsencrypt/sweb.ini:ro
            - ./certs:/etc/letsencrypt
        command: >
            --authenticator dns-sweb
            --dns-sweb-credentials /etc/letsencrypt/sweb.ini
            --dns-sweb-propagation-seconds 900
            -d example.com
            -d '*.example.com'
